# Site settings
title: bioDivRCN | Biodiversity Research Coordination Network
description: "A collabotative project about documenting, curating and prediction biodiversity"
url: "https://bioDivRCN.github.io/"
author:
  name: "bioDivRCN"
  email: "ajrominger@gmail.com"

# Build settings
baseurl:  # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
